/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransfersRouteImport } from './routes/_app.transfers'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppLabsNewRouteImport } from './routes/_app.labs.new'
import { Route as AppLabsLabIdRouteImport } from './routes/_app.labs.$labId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLabsNewRoute = AppLabsNewRouteImport.update({
  id: '/labs/new',
  path: '/labs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLabsLabIdRoute = AppLabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/transfers': typeof AppTransfersRoute
  '/labs/$labId': typeof AppLabsLabIdRoute
  '/labs/new': typeof AppLabsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/transfers': typeof AppTransfersRoute
  '/labs/$labId': typeof AppLabsLabIdRoute
  '/labs/new': typeof AppLabsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/labs/$labId': typeof AppLabsLabIdRoute
  '/_app/labs/new': typeof AppLabsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/devices'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/transfers'
    | '/labs/$labId'
    | '/labs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/devices'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/transfers'
    | '/labs/$labId'
    | '/labs/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/devices'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/transfers'
    | '/_app/labs/$labId'
    | '/_app/labs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labs/new': {
      id: '/_app/labs/new'
      path: '/labs/new'
      fullPath: '/labs/new'
      preLoaderRoute: typeof AppLabsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labs/$labId': {
      id: '/_app/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof AppLabsLabIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppLabsLabIdRoute: typeof AppLabsLabIdRoute
  AppLabsNewRoute: typeof AppLabsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppLabsLabIdRoute: AppLabsLabIdRoute,
  AppLabsNewRoute: AppLabsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
